function puzzle = loadPuzzle()

%% puzzle 
  % Letters : S M T A R E H
  % Center  : A (mandatory)
  % Rule    : minimum 4 letters, word must contain A, only use SMTAREH
  %
  % OUTPUT:
  %   puzzle.availableLetters  smtareh'
  %   puzzle.centerLetter     'a'
  %   puzzle.pangram    'hamster'
  %   puzzle.themeWords        - cell array of all valid words
  %   puzzle.wordPoints        - containers.Map of word -> point value

    puzzle.availableLetters = 'smtareh';
    puzzle.centerLetter     = 'a';
    puzzle.pangram          = 'hamster';
 
    % Word lists by length 

    fourLetters = { ...
        'ears', 'eats',  'hams', 'hare', ...
        'hart',  'mare',  'mate',  'meat',  'rats',  'tame', ...
        'rhea', ...
    };
 
    fiveLetters = { ...
        'earth',  'hares',  'harts',  'mares',  'hates',  'mates', ...
        'heart',   'meats',  'smart', ...
        'rheas', 'tamer', ...
    };
 
    sixLetters = { ...
        'earths',  'harems',  'haters',  'hearts',  'master', ...
        'tamers' , ...
    };
 
    sevenLetters = { ...
        'hamster',  ...
    };
 
    %  Assemble full theme word list 
    puzzle.themeWords = [ ...
        fourLetters, fiveLetters, sixLetters, sevenLetters ...
    ];

end
