function puzzle = loadPuzzle()

%% puzzle 
  % Letters : S M T A R E H
  % Center  : A (mandatory)
  % Rule    : minimum 4 letters, word must contain A, only use SMTAREH
  %
  % OUTPUT:
  %   puzzle.availableLetters  smtareh'
  %   puzzle.centerLetter     'a'
  %   puzzle.pangram    'hamster'
  %   puzzle.themeWords        - cell array of all valid words
  %   puzzle.wordPoints        - containers.Map of word -> point value

    puzzle.availableLetters = 'smtareh';
    puzzle.centerLetter     = 'a';
    puzzle.pangram          = 'hamster';
 
    % Word lists by length 

    fourLetters = { ...
        'ears',  'east',  'eats',  'eras',  'hams',  'hare', ...
        'hart',  'hate',  'hats',  'hear',  'heat',  'mare', ...
        'mars',  'mart',  'mash',  'mast',  'math',  'mate', ...
        'meat',  'rash',  'rate',  'rats',  'rhea',  'same', ...
        'seam',  'sear',  'seat',  'star',  'tame',  'team', ...
        'tear' , 'rame' ...
    };
 
    fiveLetters = { ...
        'earth',  'harem',  'harts',  'hater',  'hates',  'hears', ...
        'heart',  'heats',  'mares',  'maths',  'mater',  'mates', ...
        'meats',  'rates',  'rheas',  'share',  'shear',  'smart', ...
        'smear',  'stare',  'steam',  'tamer',  'tames',  'teams', ...
        'ramet',  ... 
    };
 
    sixLetters = { ...
        'earths',  'harems',  'haters',  'hearts',  'master', ...
        'maters',  'stream',  'tamers' , 'ramets' ...
    };
 
    sevenLetters = { ...
        'hamster', 'mathers' ...
    };
 
    %  Assemble full theme word list 
    puzzle.themeWords = [ ...
        fourLetters, fiveLetters, sixLetters, sevenLetters ...
    ];

end
